## Implementation of SVD in Python

### 1. Using Numpy to implement full matrix SVD

In [1]:
import numpy as np
 
#Creating a matrix A
A = np.array([[3,2,2],[2,3,-2]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A)
m, n = A.shape
A_remake = U[:,:n] @ np.diag(D) @ VT[:m,:]

#Checking if we can remake the original matrix using U,D,VT
print('U: ', U, '\n')
print('D: ', D, '\n')
print('V^T: ', VT, '\n')
print('The Matrix:', A_remake)

U:  [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 

D:  [5. 3.] 

V^T:  [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]] 

The Matrix: [[ 3.  2.  2.]
 [ 2.  3. -2.]]


### 2. Using scikit-learn to implement Truncated SVD

In [2]:
#Importing required modules
import numpy as np
from sklearn.decomposition import TruncatedSVD
 
#Creating array 
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
 
#Fitting the SVD class
trun_svd =  TruncatedSVD(n_components = 2)
A_transformed = trun_svd.fit_transform(A)
 
#Printing the transformed matrix
print("Transformed Matrix:")
print(A_transformed)

Transformed Matrix:
[[ 5.7942733  -0.46723885]
 [ 3.3604414  -1.58000033]
 [ 4.14622666  1.93351902]]
